
-- Auto-generated seed file from image_reviews.json
-- Deletes existing records to prevent conflicts (optional, but safe for initial seed)
DELETE FROM image_reviews;

INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('abb05187-c1a2-4dc7-bd3b-892fe76cd961', 'IMG_8051.jpg', 'images/backyard/IMG_8051.jpg', 'backyard', 'Zones for entertainment, layers of plants, the vines growing up over the table, the moody lighting', 'skandinaviskinteriorakademi', 'Fin måte å utnytte plassen i en mindre hage. Ulike soner gjør at hagen virker større og man får mer ut ...', '["scandinavian","small garden","outdoor rooms","gravel","dining zone","lounge","layered planting"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('e98dca9f-b63d-4f5e-b6e3-20b553070fc7', 'IMG_8052.jpg', 'images/backyard/IMG_8052.jpg', 'backyard', 'the rusted metal; would like to explore seeing this on all retaining walls.', 'dutch_belgium_gardens', 'THE ART OF GARDEN RHYTHM ...', '["garden detail","corten edging","gravel","planting bed","texture","landscape design"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('a8541772-1e5f-49cc-ba47-d5f2e027cba8', 'IMG_8053.jpg', 'images/backyard/IMG_8053.jpg', 'backyard', 'Would be an interesting look for the bioswale. The shape of it and the tall planters on its left to cover our neighbors fence.', 'dutch_belgium_gardens', 'THE ART OF GARDEN RHYTHM ...', '["formal garden","topiary","gravel path","curves","landscape design","bioswale"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('8682c6c3-afeb-426f-becc-49a40a0262d5', 'IMG_8066.jpg', 'images/backyard/IMG_8066.jpg', 'backyard', 'Interesting mix of plants with different shapes and colors; open, clean and airy vibes', 'dreammakersstudio24', 'Terraced Garden Transformation with Functional ...', '["terraced garden","outdoor dining","curved stairs","landscaping","fire pit","formal garden"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('80047db3-1d56-4220-a3a3-64c0f1258d90', 'IMG_8050.jpg', 'images/bathroom/IMG_8050.jpg', 'bathroom', 'Like the 1 piece stone vanity; wood paneling creates warm and cozy feeling; suitable concept for guest bathroom', 'memiainteriors', 'Quiet moments in material. Stone, light, and proportion working together ...', '["stone vanity","warm minimal","wall paneling","pendant lights","marble","modern"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('d85980b8-7c33-4330-9f25-f554069911ee', 'IMG_8054.jpg', 'images/bathroom/IMG_8054.jpg', 'bathroom', 'Like the moody feeling for the master bathroom; one piece stone vanity; clean and modern vibes', 'rem_designhouse', 'Haveeeee to post this on the feed because YUM right ...', '["moody","dark stone","textured tile","black faucet","integrated lighting","modern"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('aede26c3-a4af-48bc-aeff-75253e178753', 'IMG_8061.jpg', 'images/bathroom/IMG_8061.jpg', 'bathroom', 'Another one piece stone vanity concept we like; stone slab in the shower area serves almost like a statement piece', 'ashleytstark', 'Concept to design. Green as a pop and a neutral ...', '["green marble","stone vanity","skylight","modern","neutral palette","spa bathroom"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('a0fb4451-b940-4649-ad56-2eb66ee23cf6', 'IMG_8063.jpg', 'images/bathroom/IMG_8063.jpg', 'bathroom', 'Illustrates the vanity we like', 'helenlanderstone', 'Natural stone vanity with drawer #washroomsink...', '["marble vanity","brass faucet","vanity unit","natural stone","washroom sink","product"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('6f4c2d3c-d7c8-441b-9a64-e1b222179d53', 'IMG_8067.jpg', 'images/bathroom/IMG_8067.jpg', 'bathroom', 'modern and moody concept for master bathroom; love the wall-mounted faucets - clean and sophisticated look; one piece stone vanity', 'thesplashlabofficial', 'The Aerofoil is a precision-engineered washplane ...', '["commercial restroom","washplane","black stone","copper fixtures","industrial","minimalist"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('55aba89d-ea53-43a4-99cd-ce72f5376f96', 'IMG_8068.jpg', 'images/bathroom/IMG_8068.jpg', 'bathroom', 'Illustrates the wall-mounted faucets and one piece stone vanity - the look we are pursuing', 'sulinadesignstudio', 'An extraordinary twist of modern luxury and cozy vintage ...', '["green marble","stone sink","modern luxury","cozy vintage","moody","spa"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('821cac03-d67f-41b1-abc6-67df74175630', 'IMG_8069.jpg', 'images/bathroom/IMG_8069.jpg', 'bathroom', 'Want the shower drain to seamlessly blend into the shower pan', 'infinitydrain', 'What truly distinguishes Infinity Drain is our ...', '["shower drain","fixtures","product display","modern","satin metal","bathroom hardware"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('0cf611d0-ddf9-415d-8c29-36b5f9e01eae', 'IMG_8070.jpg', 'images/bathroom/IMG_8070.jpg', 'bathroom', 'Concealed storage to store bathroom essentials and cleaning supplies to create a clean and clutter free bathroom look', 'jimthebathroomguy', 'One of the most common frustrations renovators ...', '["bathroom storage","concealed niche","stone tile","renovation trend","functional"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('05469a63-901c-48ab-aa4d-beac50646383', 'IMG_8059.jpg', 'images/bedroom/IMG_8059.jpg', 'bedroom', 'Like the curvy and rounded walls/columns; like how the bathroom flooring and vanity sink are of the same design and material; like how the ceiling and wall colors are the same and does not make the room looks compressed', 'vogueliving', '"Classic influences were paired with a contemporary interpretation of traditional detailing, resulting in an ...', '["contemporary classic","ensuite","stone","curved column","herringbone floor","luxury"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('cdbf0156-cf0a-4e68-8f3e-2bb50b7d749c', 'IMG_8055.jpg', 'images/kitchen/IMG_8055.jpg', 'kitchen', 'Like the darker walnut cabinet color but nothing else', 'jamie_antonuccio_official', 'Flush please 😂😂 not what you think!!', '["organic modern","emerald stone","wood cabinetry","flush detail","countertop","modern"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('c042eb94-1be2-4f99-9010-d4872d18262d', 'IMG_8056.jpg', 'images/kitchen/IMG_8056.jpg', 'kitchen', 'Like the darker cabinet color; like the backsplash to shelf; prefer not to have upper cabinets and go for the backsplash to shelf look', 'victoria.douyere', 'Retour sur le projet PORT LYMPIA. Rénovation complète et décoration d’un ...', '["parisian","marble backsplash","wood cabinetry","compact kitchen","classic-modern","renovation"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('6fe968df-4bba-4f16-909d-6e9a62bd7c67', 'IMG_8062.jpg', 'images/kitchen/IMG_8062.jpg', 'kitchen', 'Like the clean look of the cabinets - no handles and unnecessary designs on the cabinets', 'incraftinterior and anca.murgescu', 'See more', '["dishwasher","aeg","modern kitchen","appliance detail","flush cabinet","utility"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('1141bb36-1e0e-41bf-8eb4-806feca9b42e', 'IMG_8064.jpg', 'images/kitchen/IMG_8064.jpg', 'kitchen', 'the integrated sync with carve out shelf is really nice', 'nsbuilders', 'Danby Sink | Vola Tapware ...', '["marble sink","integrated sink","vola tapware","custom stone","modern","craftsmanship"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('a4047a41-3128-4221-8353-35cdad4f6cb1', 'IMG_8065.jpg', 'images/kitchen/IMG_8065.jpg', 'kitchen', 'the integrated sync with carve out shelf is really nice', 'nsbuilders', 'Danby Sink | Vola Tapware ...', '["marble sink","integrated sink","vola tapware","custom stone","modern","craftsmanship"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('c20b6a3b-fe66-4d37-a777-6127186d972b', 'IMG_8071.jpg', 'images/kitchen/IMG_8071.jpg', 'kitchen', 'Color of the cabinets is nice and the framing of the cabinet with dark stone i nice. but we are not fans of the hardware or finishing of the wood or anything else in this photo.', 'workstead', 'WORLD OF WOOD | At the Soho Residence, wood brings order and intention to the openness of loft ...', '["warm wood","bespoke cabinetry","organic modern","japandi","minimalist","natural materials"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('bac4d29b-a300-4bca-8ad6-a10e29caf0be', 'IMG_8072.jpg', 'images/kitchen/IMG_8072.jpg', 'kitchen', '', 'modulnova_official and modulnovamiami', 'Modulnova Miami ...', '["modern","dark wood","black marble","hidden storage","luxury","minimalist"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('4d68e37e-bc62-42e9-a5b1-8800146b1947', 'IMG_8073.jpg', 'images/kitchen/IMG_8073.jpg', 'kitchen', '', 'avenue_home_decor', 'Elegant Interior Design 😍 ...', '["modern","warm wood","dark countertop","integrated lighting","minimalist","luxury"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('759d9c35-fbfa-4733-a5cb-06834fe6dff8', 'IMG_8074.jpg', 'images/kitchen/IMG_8074.jpg', 'kitchen', '', 'deeluxecasa', 'Dark and white kitchen bar design ...', '["modern","black-and-white","kitchen island","marble","city view","ambient lighting"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('6940142e-71ac-4bea-a389-8f38e969a521', 'IMG_8075.jpg', 'images/kitchen/IMG_8075.jpg', 'kitchen', '', 'luxurydreamhub', 'Cooking under the canopy of dreams. 🌳✨🍳 ...', '["modern","glass roof","nature-integrated","warm wood","luxury","indoor-outdoor"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('d0d429df-098a-4f28-aac5-7805bcc5dc98', 'IMG_8057.jpg', 'images/patio/IMG_8057.jpg', 'patio', '', 'maisonbaliinteriors', 'Build your sanctuary with us ↧ ...', '["tropical","resort","pool deck","dark exterior","lounge chairs","modern","bali"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('90fae00f-b355-476e-82bc-0f35129c6d11', 'IMG_8058.jpg', 'images/patio/IMG_8058.jpg', 'patio', '', 'maisonbaliinteriors', 'Build your sanctuary with us ↧ ...', '["tropical","resort","pool","dark wood","indoor-outdoor","modern","bali"]', CURRENT_TIMESTAMP);
INSERT INTO image_reviews (id, filename, path, room, note, ig_account, visible_caption, tags, updated_at) VALUES ('bd5c0db3-bebf-4833-b02d-a30f1860e1d7', 'IMG_8060.jpg', 'images/stairway/IMG_8060.jpg', 'stairway', '', 'jasonowyong', 'No visible caption; Instagram story screenshot.', '["dark wood","stone treads","stair detail","modern","contrast","material transition"]', CURRENT_TIMESTAMP);
