/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 8377b4937246416b307c9caa85c601b2)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/_worker");
		durableNamespaces: "RenovationAgent" | "EstimateCollabHub";
	}
	interface Env {
		CACHE: KVNamespace;
		SESSIONS: KVNamespace;
		ARTIFACTS_BUCKET: R2Bucket;
		DB: D1Database;
		VECTOR_INDEX: VectorizeIndex;
		GITHUB_TOKEN: SecretsStoreSecret;
		CLOUDFLARE_ACCOUNT_ID: SecretsStoreSecret;
		CLOUDFLARE_IMAGES_STREAM_TOKEN: SecretsStoreSecret;
		CF_IMAGES_TOKEN: SecretsStoreSecret;
		CLOUDFLARE_WRANGLER_API_TOKEN: SecretsStoreSecret;
		CLOUDFLARE_AI_SEARCH_TOKEN: SecretsStoreSecret;
		CLOUDFLARE_OBSERVABILITY_TOKEN: SecretsStoreSecret;
		WORKER_API_KEY: SecretsStoreSecret;
		AGENTIC_WORKER_API_KEY: SecretsStoreSecret;
		AI_GATEWAY_TOKEN: SecretsStoreSecret;
		CF_BROWSER_RENDER_TOKEN: SecretsStoreSecret;
		JULES_API_KEY: SecretsStoreSecret;
		GEMINI_API_KEY: SecretsStoreSecret;
		ANTHROPIC_API_KEY: SecretsStoreSecret;
		AI: Ai;
		ASSETS: Fetcher;
		AI_GATEWAY_ID: "default-gateway";
		RENOVATION_AGENT: DurableObjectNamespace<import("./src/_worker").RenovationAgent>;
		ESTIMATE_COLLAB: DurableObjectNamespace<import("./src/_worker").EstimateCollabHub>;
		IMAGE_PROCESSING_WORKFLOW: Workflow<Parameters<import("./src/_worker").ImageProcessingWorkflow['run']>[0]['payload']>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_GATEWAY_ID">> {}
}
