/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bb73541cba73cd36d4736e93f696094b)
interface __BaseEnv_Env {
	CACHE: KVNamespace;
	SESSIONS: KVNamespace;
	OAUTH_KV: KVNamespace;
	ARTIFACTS_BUCKET: R2Bucket;
	DB: D1Database;
	VECTOR_INDEX: VectorizeIndex;
	RESEARCH_INDEX: VectorizeIndex;
	PHOTO_INDEX: VectorizeIndex;
	EMAIL: SendEmail;
	GITHUB_TOKEN: SecretsStoreSecret;
	CLOUDFLARE_ACCOUNT_ID: SecretsStoreSecret;
	CLOUDFLARE_IMAGES_STREAM_TOKEN: SecretsStoreSecret;
	CF_IMAGES_TOKEN: SecretsStoreSecret;
	CLOUDFLARE_WRANGLER_API_TOKEN: SecretsStoreSecret;
	WORKER_API_KEY: SecretsStoreSecret;
	AI_GATEWAY_TOKEN: SecretsStoreSecret;
	CF_BROWSER_RENDER_TOKEN: SecretsStoreSecret;
	JULES_API_KEY: SecretsStoreSecret;
	GEMINI_API_KEY: SecretsStoreSecret;
	ANTHROPIC_API_KEY: SecretsStoreSecret;
	FAL_API_KEY: SecretsStoreSecret;
	REPLICATE_API_TOKEN: SecretsStoreSecret;
	GOOGLE_MAPS_API: SecretsStoreSecret;
	GOOGLE_SEARCH_API_KEY: SecretsStoreSecret;
	CLICKUP_TOKEN: SecretsStoreSecret;
	CLICKUP_TEAM_ID: SecretsStoreSecret;
	GOOGLE_CREDS_SA_PRIVATE_KEY_PT_1: SecretsStoreSecret;
	GOOGLE_CREDS_SA_PRIVATE_KEY_PT_2: SecretsStoreSecret;
	GOOGLE_CREDS_SA_CLIENT_EMAIL: SecretsStoreSecret;
	LOADER: WorkerLoader;
	AI: Ai;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	AI_GATEWAY_ID: "default-gateway";
	CLICKUP_LIST_ID: "901714811766";
	GOOGLE_SEARCH_CX: "";
	RENOVATION_AGENT: DurableObjectNamespace<import("./src/_worker").RenovationAgent>;
	BUDGET_AGENT: DurableObjectNamespace<import("./src/_worker").BudgetAgent>;
	ESTIMATE_COLLAB: DurableObjectNamespace<import("./src/_worker").EstimateCollabHub>;
	A2A_V2: DurableObjectNamespace<import("./src/_worker").GAS_A2A>;
	BID_PORTFOLIO_AGENT: DurableObjectNamespace<import("./src/_worker").BidPortfolioAgent>;
	RESEARCH_AGENT: DurableObjectNamespace<import("./src/_worker").ResearchAgent>;
	PERMIT_INTELLIGENCE_AGENT: DurableObjectNamespace<import("./src/_worker").PermitIntelligenceAgent>;
	SHOWROOM_RESEARCH_AGENT: DurableObjectNamespace<import("./src/_worker").ShowroomResearchAgent>;
	FLOORPLAN_SESSION: DurableObjectNamespace<import("./src/_worker").FloorplanSessionDO>;
	DEEP_RESEARCH_AGENT: DurableObjectNamespace<import("./src/_worker").DeepResearchAgent>;
	REMODEL_ORCHESTRATOR: DurableObjectNamespace<import("./src/_worker").RemodelOrchestrator>;
	ADMIN_CHAT_AGENT: DurableObjectNamespace<import("./src/_worker").AdminChatAgent>;
	REMODEL_MCP: DurableObjectNamespace /* RemodelMcpAgent */;
	IMAGE_PROCESSING_WORKFLOW: Workflow<Parameters<import("./src/_worker").ImageProcessingWorkflow['run']>[0]['payload']>;
	CHECKLIST_RATIONALE_WORKFLOW: Workflow<Parameters<import("./src/_worker").ChecklistRationaleWorkflow['run']>[0]['payload']>;
	IMAGE_BATCH_WORKFLOW: Workflow<Parameters<import("./src/_worker").ImageBatchProcessingWorkflow['run']>[0]['payload']>;
	SHOWROOM_SCRAPE_WORKFLOW: Workflow<Parameters<import("./src/_worker").ShowroomScrapeWorkflow['run']>[0]['payload']>;
	BRAND_RESEARCH_WORKFLOW: Workflow<Parameters<import("./src/_worker").BrandResearchWorkflow['run']>[0]['payload']>;
	PRODUCT_RESEARCH_WORKFLOW: Workflow<Parameters<import("./src/_worker").ProductResearchWorkflow['run']>[0]['payload']>;
	DEEP_RESEARCH_JOB_WORKFLOW: Workflow<Parameters<import("./src/_worker").DeepResearchJobWorkflow['run']>[0]['payload']>;
	BLANK_CANVAS_WORKFLOW: Workflow<Parameters<import("./src/_worker").BlankCanvasBatchWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/_worker");
		durableNamespaces: "RenovationAgent" | "EstimateCollabHub" | "GAS_A2A" | "BudgetAgent" | "BidPortfolioAgent" | "ResearchAgent" | "PermitIntelligenceAgent" | "ShowroomResearchAgent" | "FloorplanSessionDO" | "DeepResearchAgent" | "RemodelOrchestrator" | "AdminChatAgent" | "RemodelMcpAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_GATEWAY_ID" | "CLICKUP_LIST_ID" | "GOOGLE_SEARCH_CX">> {}
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}