/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 652eaa324ab92caa617ba4fa06de4a03)
interface __BaseEnv_Env {
	CACHE: KVNamespace;
	SESSIONS: KVNamespace;
	ARTIFACTS_BUCKET: R2Bucket;
	DB: D1Database;
	VECTOR_INDEX: VectorizeIndex;
	RESEARCH_INDEX: VectorizeIndex;
	PHOTO_INDEX: VectorizeIndex;
	GITHUB_TOKEN: SecretsStoreSecret;
	CLOUDFLARE_ACCOUNT_ID: SecretsStoreSecret;
	CLOUDFLARE_IMAGES_STREAM_TOKEN: SecretsStoreSecret;
	CF_IMAGES_TOKEN: SecretsStoreSecret;
	CLOUDFLARE_WRANGLER_API_TOKEN: SecretsStoreSecret;
	WORKER_API_KEY: SecretsStoreSecret;
	CLOUDFLARE_AI_GATEWAY_TOKEN: SecretsStoreSecret;
	CF_BROWSER_RENDER_TOKEN: SecretsStoreSecret;
	JULES_API_KEY: SecretsStoreSecret;
	GEMINI_API_KEY: SecretsStoreSecret;
	ANTHROPIC_API_KEY: SecretsStoreSecret;
	FAL_API_KEY: SecretsStoreSecret;
	REPLICATE_API_TOKEN: SecretsStoreSecret;
	GOOGLE_MAPS_API: SecretsStoreSecret;
	GOOGLE_SEARCH_API_KEY: SecretsStoreSecret;
	CLICKUP_TOKEN: SecretsStoreSecret;
	CLICKUP_TEAM_ID: SecretsStoreSecret;
	LOADER: WorkerLoader;
	AI: Ai;
	ASSETS: Fetcher;
	AI_GATEWAY_ID: "core-remodel";
	CLICKUP_LIST_ID: "901714811766";
	SODA_API_KEY_ID: string;
	SODA_API_KEY_SECRET: string;
	SODA_APP_TOKEN: string;
	SODA_APP_TOKEN_SECRET: string;
	RENOVATION_AGENT: DurableObjectNamespace<import("./src/_worker").RenovationAgent>;
	BUDGET_AGENT: DurableObjectNamespace<import("./src/_worker").BudgetAgent>;
	ESTIMATE_COLLAB: DurableObjectNamespace<import("./src/_worker").EstimateCollabHub>;
	A2A_V2: DurableObjectNamespace<import("./src/_worker").GAS_A2A>;
	BID_PORTFOLIO_AGENT: DurableObjectNamespace<import("./src/_worker").BidPortfolioAgent>;
	RESEARCH_AGENT: DurableObjectNamespace<import("./src/_worker").ResearchAgent>;
	PERMIT_INTELLIGENCE_AGENT: DurableObjectNamespace<import("./src/_worker").PermitIntelligenceAgent>;
	SHOWROOM_RESEARCH_AGENT: DurableObjectNamespace<import("./src/_worker").ShowroomResearchAgent>;
	FLOORPLAN_SESSION: DurableObjectNamespace<import("./src/_worker").FloorplanSessionDO>;
	DEEP_RESEARCH_AGENT: DurableObjectNamespace<import("./src/_worker").DeepResearchAgent>;
	REMODEL_ORCHESTRATOR: DurableObjectNamespace<import("./src/_worker").RemodelOrchestrator>;
	ADMIN_CHAT_AGENT: DurableObjectNamespace<import("./src/_worker").AdminChatAgent>;
	IMAGE_PROCESSING_WORKFLOW: Workflow<Parameters<import("./src/_worker").ImageProcessingWorkflow['run']>[0]['payload']>;
	CHECKLIST_RATIONALE_WORKFLOW: Workflow<Parameters<import("./src/_worker").ChecklistRationaleWorkflow['run']>[0]['payload']>;
	IMAGE_BATCH_WORKFLOW: Workflow<Parameters<import("./src/_worker").ImageBatchProcessingWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/_worker");
		durableNamespaces: "RenovationAgent" | "EstimateCollabHub" | "GAS_A2A" | "BudgetAgent" | "BidPortfolioAgent" | "ResearchAgent" | "PermitIntelligenceAgent" | "ShowroomResearchAgent" | "FloorplanSessionDO" | "DeepResearchAgent" | "RemodelOrchestrator" | "AdminChatAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_GATEWAY_ID" | "CLICKUP_LIST_ID" | "SODA_API_KEY_ID" | "SODA_API_KEY_SECRET" | "SODA_APP_TOKEN" | "SODA_APP_TOKEN_SECRET">> {}
}
