-- Columns description, reviewed, reviewed_at already exist on the remote images table.
-- This migration was originally generated by drizzle-kit but the ALTER TABLEs collide
-- with a prior manual apply. Replaced with a no-op SELECT to satisfy the migration runner.
SELECT 1;