-- Backfill drive_lists.notes: legacy single-chunk text → JSON array of note
-- cards (split on blank lines). Idempotent: only touches rows not already JSON.
UPDATE drive_lists SET notes = '["Designer at 10am (done ~noon). City Lights closes 4pm Sat — do it FIRST and budget 1–2 hrs. Both appliance stops are in Redwood City ~0.5 mi apart; Davies closes 3pm (optional — only if you arrive by ~2:30, hit it before Homewise). Homewise RWC stays open to 6. East Bay alternative if you''d rather not drive the Peninsula: Homewise Emeryville (#65, Sat 10–6). All appliance stops carry panel-ready dishwashers + wall ovens."]' WHERE slug = 'sat-lighting-appliances-sf-peninsula' AND notes NOT LIKE '[%';
--> statement-breakpoint
UPDATE drive_lists SET notes = '["TIMING: Designer ~10am at the house (est. done 11:30–12). This drive fits the designer day well — City Lights is open until 4pm and Homewise RWC until 6pm, so a noon start works.","SEQUENCE NOTE: The high-end appliance rooms (Davies, CG Daly City) both CLOSE AT 3PM. If seeing those matters more than lighting, flip the order — do appliances first, then City Lights (open till 4). On the designer day the 10am start makes an early appliance run hard, so the default below is Lighting → Homewise RWC (the one appliance stop open late).","DATE CHECK: You said \"tomorrow\" but \"Saturday hours.\" Tomorrow (Sun 7/12) most of these are CLOSED (City Lights closed Sun; Homewise RWC open Sun 10–6). Hours below are SATURDAY. Confirm the actual date and I''ll adjust.","All appliance stops carry panel-ready dishwashers (Bosch/Miele/Thermador) and wall ovens."]' WHERE slug = 'lighting-appliances-designer-day-sf-peninsula' AND notes NOT LIKE '[%';
--> statement-breakpoint
UPDATE drive_lists SET notes = '["⚠️ HARD SCHEDULING CONSTRAINT: San Jose stone yards close very early Saturday — Daltile 1pm, All Natural Stone 2pm, Marble Creations 2pm, Carmel & Bedrosians 3pm. ALL stone must happen 9am–2pm. That does NOT fit the same day as the 10am SF designer + ~50-min drive (you''d arrive ~1pm with ANS already closing). Recommendation: run this drive on its own free Saturday, leaving SF by ~8:30–9am. If it must be the designer day, skip Carmel + Daltile and go STRAIGHT to All Natural Stone to catch the slab before 2pm.","⭐ PRIORITY: The ~$30 Rosso Levanto (\"red ross lavaso\") slab at All Natural Stone SJ — you''re ready to buy. CALL AHEAD (408-544-9600) to confirm it''s still available and ask them to hold it, so you''re not racing the 2pm close.","CALACATTA VIOLA + INVISACOOK mapping: natural Calacatta Viola slab sources → Carmel, All Natural Stone, Marble Creations. InvisaCook-compatible (cook-through) porcelain/sintered that can match it → Carmel (Neolith), Bedrosians (Magnifica porcelain slabs), Daltile (porcelain panels). Bonus goal — a porcelain that visually matches Viola — check Bedrosians Magnifica + Carmel Neolith first.","DATE CHECK: You said \"tomorrow\" but \"Saturday hours.\" Tomorrow (Sun 7/12) nearly everything here is CLOSED. Hours below are SATURDAY — confirm the date and I''ll adjust.","All appliance stops carry panel-ready DW + wall ovens."]' WHERE slug = 'south-bay-stone-fabricators-appliances-doors' AND notes NOT LIKE '[%';
--> statement-breakpoint
UPDATE drive_lists SET notes = '["Broken out from the South Bay drive so you can hit these two chains closer to home. Both are Hayward/San Leandro and ~15 min apart.","CARMEL STONE: no East Bay location — only Palo Alto, so it stays on the South Bay drive.","HOURS: both close early Saturday (Daltile 1pm, Bedrosians 2pm) — same morning-only pattern as the South Bay stone yards. Date/day still needs confirming (see the other drives).","PAIRS WELL WITH: your already-visited San Leandro cluster on Teagarden St — Walker Zanger (#82), Stone Empire (#83), New Century K&B (#85) — plus Tez Marble in Oakland (#46), if you want to make a fuller East Bay stone day.","WHAT EACH IS FOR: Daltile = porcelain panels (InvisaCook-compatible) + slabs, but trade-only — you can browse and tag/hold slabs, purchase routes through your contractor/fabricator. Bedrosians = Magnifica porcelain slabs (best InvisaCook + Calacatta-look match) and a walk-in-friendly, homeowner-welcome floor."]' WHERE slug = 'east-bay-stone-daltile-bedrosians' AND notes NOT LIKE '[%';
