CREATE TABLE `bucket_product_candidates` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`bucket_id` integer NOT NULL,
	`rank` integer DEFAULT 0 NOT NULL,
	`confidence` integer,
	`brand_id` integer,
	`brand_name_raw` text,
	`product_name` text,
	`model_number` text,
	`sku` text,
	`product_url` text,
	`category` text,
	`style` text,
	`price_text` text,
	`sale_price_text` text,
	`discount_text` text,
	`image_source_urls` text,
	`pdf_source_urls` text,
	`colors` text,
	`rationale` text,
	`raw_extraction` text,
	`is_match` integer,
	`liked` integer,
	`stars` integer,
	`reaction_transcript` text,
	`reaction_summary` text,
	`status` text DEFAULT 'pending' NOT NULL,
	`confirmed_product_id` integer,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`bucket_id`) REFERENCES `product_photo_buckets`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`brand_id`) REFERENCES `brands`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE INDEX `bucket_product_candidates_bucket_idx` ON `bucket_product_candidates` (`bucket_id`);