-- NOTE: drizzle-kit also diffed in a CREATE TABLE `health_email_loopback` here,
-- because that table (created by migration 0135) was missing from the 0136
-- cumulative snapshot — pre-existing drift, not part of this change. The table
-- already exists on remote, so re-creating it here would be a spurious no-op.
-- The 0138 snapshot regenerated by this run now includes it, healing the drift;
-- only the intended index remains in this .sql. (Renumbered 0137→0138: a
-- concurrent session's unmerged 0137_glamorous_microchip already claimed 0137
-- on the shared remote D1.)
CREATE UNIQUE INDEX `brands_name_key_uniq` ON `brands` (replace(replace(replace(lower(trim("name")),' ',''),'.',''),',','')) WHERE "brands"."is_active" = 1;