import { sql } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

/**
 * System-level alerts generated by the RemodelOrchestrator agent.
 * These are project-wide risks (e.g., critical path slip),
 * not specific to a single task.
 *
 * Alerts appear as a banner on the tasks page and are acknowledged
 * manually by the user. No push notifications or emails.
 */
export const clickupSystemAlerts = sqliteTable("clickup_system_alerts", {
  id: integer("id").primaryKey({ autoIncrement: true }),

  /** project_delay | resource_conflict | budget_risk | general */
  alertType: text("alert_type").notNull(),

  /** critical | warning | info */
  severity: text("severity").notNull().default("warning"),

  /** Human-readable alert message. */
  message: text("message").notNull(),

  /** JSON metadata: affected task IDs, projected delay days, etc. */
  metadata: text("metadata"),

  /** The audit run ID that generated this alert. */
  auditRunId: text("audit_run_id"),

  /** false = active, true = acknowledged by user. */
  acknowledged: integer("acknowledged", { mode: "boolean" })
    .notNull()
    .default(false),

  acknowledgedAt: text("acknowledged_at"),

  createdAt: text("created_at")
    .notNull()
    .default(sql`(datetime('now'))`),
});
