/**
 * @fileoverview Cloudflare Workers entry point
 *
 * This file integrates the Hono API with Astro SSR.
 */

// @ts-ignore - this file is generated by Astro after build
import astroHandler from "../dist/_worker.js/index.js";
import { app as honoApp } from "./backend/api/index";
import { isRequestAuthenticated } from "./backend/utils/access";

// Export Durable Object agents for Cloudflare Workers runtime
export { RenovationAgent } from "./backend/ai/agents/RenovationAgent";
export { EstimateCollabHub } from "./backend/realtime/EstimateCollabHub";

const handler: ExportedHandler<Env> = {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const protectedPaths = ["/admin", "/uploads", "/photo-edits"];

    const isProtectedPath = protectedPaths.some(
      (path) => url.pathname === path || url.pathname.startsWith(`${path}/`),
    );

    if (url.pathname.startsWith("/api/realtime/estimates")) {
      const room = url.searchParams.get("room")?.trim() || "global";
      const id = env.ESTIMATE_COLLAB.idFromName(room);
      const stub = env.ESTIMATE_COLLAB.get(id);
      return stub.fetch(request);
    }

    // Handle API routes with Hono
    if (
      url.pathname.startsWith("/api/") ||
      url.pathname === "/openapi.json" ||
      url.pathname === "/swagger" ||
      url.pathname === "/scalar" ||
      url.pathname === "/docs" ||
      url.pathname === "/context"
    ) {
      return honoApp.fetch(request, env, ctx);
    }

    if (isProtectedPath) {
      const authenticated = await isRequestAuthenticated(request, env);
      if (!authenticated) {
        const redirect = new URL("/access", url.origin);
        redirect.searchParams.set("next", `${url.pathname}${url.search}`);
        return Response.redirect(redirect.toString(), 302);
      }
    }

    // Let Astro handle everything else (SSR and static assets via env.ASSETS)
    return astroHandler.fetch!(request, env, ctx);
  },
};

export default handler;
