/**
 * @fileoverview Cloudflare Workers entry point
 *
 * This file integrates the Hono API with Astro SSR.
 */

import { app as honoApp } from "./backend/api/index";
import { runPermitSync } from "./backend/services/dbi/permits-sync.js";
import { dispatchDueWorkflows } from "./backend/services/workflow-dispatcher";
import { autoHealImageUploads } from "./backend/services/image-processor/auto-heal";
import { isRequestAuthenticated } from "./backend/utils/access";
import { routeAgentRequest } from "agents";
// @ts-ignore - this file is generated by Astro after build
import astroHandler from "../dist/_worker.js/index.js";

// Export Durable Object agents for Cloudflare Workers runtime
export { RenovationAgent } from "./backend/ai/agents/RenovationAgent";
export { BudgetAgent } from "./backend/ai/agents/BudgetAgent";
export { BidPortfolioAgent } from "./backend/ai/agents/BidPortfolioAgent";
export { EstimateCollabHub } from "./backend/realtime/EstimateCollabHub";
export { GAS_A2A } from "./backend/a2a-v2/server";
export { ImageProcessingWorkflow } from "./backend/services/image-processor/workflow.js";
export { ImageBatchProcessingWorkflow } from "./backend/services/image-processor/batch-workflow";
export { ChecklistRationaleWorkflow } from "./backend/services/checklist-rationale-workflow";
export { ResearchAgent } from "./backend/ai/agents/ResearchAgent";
export { PermitIntelligenceAgent } from "./backend/ai/agents/PermitIntelligenceAgent/index";
export { ShowroomResearchAgent } from "./backend/ai/agents/ShowroomResearchAgent/index";

const handler: ExportedHandler<Env> = {
  async fetch(request, env, ctx) {
    const agentResponse = await routeAgentRequest(request, env);
    if (agentResponse) return agentResponse;

    const url = new URL(request.url);
    const protectedPaths = [
      "/admin",
      "/uploads",
      "/photo-edits",
      "/review",
      "/budget-tracker",
      "/budget-dashboard",
    ];

    const isProtectedPath = protectedPaths.some(
      (path) => url.pathname === path || url.pathname.startsWith(`${path}/`),
    );

    if (url.pathname.startsWith("/api/realtime/estimates")) {
      const room = url.searchParams.get("room")?.trim() || "global";
      const id = env.ESTIMATE_COLLAB.idFromName(room);
      const stub = env.ESTIMATE_COLLAB.get(id);
      return stub.fetch(request);
    }

    // Handle API routes with Hono
    if (
      url.pathname.startsWith("/api/") ||
      url.pathname === "/api-docs" ||
      url.pathname === "/openapi.json" ||
      url.pathname === "/swagger" ||
      url.pathname === "/scalar" ||
      url.pathname === "/context"
    ) {
      return honoApp.fetch(request, env, ctx);
    }

    if (isProtectedPath) {
      const authenticated = await isRequestAuthenticated(request, env);
      if (!authenticated) {
        const redirect = new URL("/access", url.origin);
        redirect.searchParams.set("next", `${url.pathname}${url.search}`);
        return Response.redirect(redirect.toString(), 302);
      }
    }

    // Let Astro handle everything else (SSR and static assets via env.ASSETS)
    return astroHandler.fetch!(request, env, ctx);
  },
  async scheduled(event, env, ctx) {
    // Gate by cron expression so each registered trigger fires its own job.
    // The existing 14:00 UTC trigger runs the permit sync; the new master-tick
    // "* * * * *" reads `system_cron_schedules` and fires any due workflows.
    if (event.cron === "0 14 * * *") {
      ctx.waitUntil(runPermitSync(env));
      return;
    }
    if (event.cron === "* * * * *") {
      ctx.waitUntil(dispatchDueWorkflows(env));
      // Self-heal image uploads stranded by transient Workers AI capacity
      // errors (or whose workflow never started) without manual reprocessing.
      ctx.waitUntil(autoHealImageUploads(env));
      return;
    }
    // Unknown trigger — log and ignore.
    console.warn(`scheduled: unhandled cron "${event.cron}"`);
  },
};

export default handler;
