name: Deploy Apps Script
on:
  push:
    branches:
      - main
    paths:
      - 'src/appsscript/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm ci
          npm install -g @google/clasp

      # cat ~/.clasprc.json | pbcopy
      - name: Authenticate Clasp
        run: |
          echo "$CLASP_JSON" > ~/.clasprc.json
        env:
          CLASP_TOKEN: ${{ secrets.CLASP_JSON }}

      - name: Push Code to Apps Script
        run: |
          cd src/appsscript
          clasp push --force
